export const FONTS = [
  { label: '預設字型', value: '' },
  { label: '思源黑體', value: 'SourceHanSans' },
  { label: '思源宋體', value: 'SourceHanSerif' },
  { label: '文鼎PL楷體', value: 'WenDingPLKaiTi' },
  { label: '文鼎PL宋體', value: 'WenDingPLSongTi' },
  { label: '朱雀仿宋', value: 'ZhuQueFangSong' },
  { label: '霞鶩文楷', value: 'LXGWWenKai' },
  { label: '霞鶩新致宋', value: 'LXGWNeoZhiSong' },
  { label: '霞鶩新晰黑', value: 'LXGWNeoXiHei' },
  { label: '阿里巴巴普惠體', value: 'AlibabaPuHuiTi' },
  { label: '得意黑', value: 'DeYiHei' },
  { label: 'MiSans', value: 'MiSans' },
  { label: 'Source Serif 4', value: 'SourceSerif4' },
  { label: 'JetBrains Mono', value: 'JetBrainsMono' },
  { label: 'Literata', value: 'Literata' },
  { label: 'Inter', value: 'Inter' },
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Open Sans', value: 'OpenSans' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Source Sans Pro', value: 'SourceSansPro' },
  { label: 'Merriweather', value: 'Merriweather' },
  { label: 'Lato', value: 'Lato' },
]